### ISSUE TITLE
zhpl `sort: Illegal byte sequence`

### ISSUE THREAD

**Issue by clehene** [wulfgarpro/history-sync#11]
It's unclear to me how this chooses which gpg key to use as the documentation doesn't mention that.
I used this as a supplement https://medium.com/@jonas.elan/keeping-zsh-history-synchronized-across-multiple-environments-f1922fdef275

`zhps` works
`zhpl` throws 
```
Already up to date.
gpg: encrypted with 2048-bit RSA key, ID ABC, created 2020-01-30
      "name <email@email.com>"
gpg: Signature made Thu Jan 30 12:55:16 2020 PST
gpg:                using RSA key XYZ
gpg: Good signature from "name <email@email.com>" [ultimate]
sort: Illegal byte sequence
```

**Comment by xxb** [comment]
LANG=C
