### ISSUE TITLE
Error when committing

### ISSUE THREAD

**Issue by indigoblueraspberry** [wulfgarpro/history-sync#13]
I got the following error when committing:

`fatal: bad boolean config value 'null' for 'commit.gpgsign'`

I think this might be due to the fact that the .gitconfig file is being modified by another tool such as Gitkraken.

As it adds the following lines:

```
[gpg]
	program = null
[commit]
	gpgSign = null
[tag]
	forceSignAnnotated = null
```

When commented the error goes away and I can commit again.

Is there a way to ignore this lines from the history-sync perspective?

**Comment by wulfgarpro** [comment]
You have an invalid .gitconfig. This isn't a problem with history-sync as much as a problem with your .gitconfig, prevent history-sync from using `git`. No, history-sync has no native way of ignoring this. I'd recommend you fix your .gitconfig so that `git` works as expected.
