### ISSUE TITLE
run zhpl show message 'No such file or directory'

### ISSUE THREAD

**Issue by metroruby** [wulfgarpro/history-sync#18]
zhpl
/Users/xxx/.zsh_history -> /Users/xxx/.zsh_history.backup
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), 98.79 KiB | 232.00 KiB/s, done.
From github.com:metroruby/history-sync
   5dead8b..46a5841  main       -> origin/main
Updating 5dead8b..46a5841
Fast-forward
 zsh_history | 4083 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------
 1 file changed, 2042 insertions(+), 2041 deletions(-)
gpg: encrypted with rsa4096 key, ID AA0A2C81956100E1, created 2022-06-06
      "history sync <xxx@gmail.com>"
gpg: Signature made Tue Jun  7 09:12:49 2022 +07
gpg:                using RSA key 6922AD2C317465B1DAD1BE97A33E98A21AB609AF
gpg: Good signature from "history sync <xxx@gmail.com>" [ultimate]
sed: 1: ":a;N;$!ba;s/\n/ qkTk6f8 ...": unused label 'a;N;$!ba;s/\n/ qkTk6f8AyWECSK5kPLklo9ff30xnnZOC /g'
sed: 1: ":a;N;$!ba;s/\n/ qkTk6f8 ...": unused label 'a;N;$!ba;s/\n/ qkTk6f8AyWECSK5kPLklo9ff30xnnZOC /g'
sed: isarutle/.zsh_history: No such file or directory

I run `zhps` is done. but run `zhpl` is error that the above information.

Please suggest.

thanks.

**Comment by wulfgarpro** [comment]
Did you resolve your problem?
