### ISSUE TITLE
Error msg running with M1 OSX

### ISSUE THREAD

**Issue by yeochinyi** [wulfgarpro/history-sync#19]
>> zhpl
/Users/yeochinyi/.zsh_history -> /Users/yeochinyi/.zsh_history.backup
Already up to date.
gpg: encrypted with rsa4096 key, ID DD238E35FB755FD1, created 2022-07-21
      "Chris Yeo <yeochinyi@gmail.com>"
gpg: Signature made Thu Jul 21 20:55:20 2022 +08
gpg:                using RSA key 618331508297A026D8FE87730D0C5A4A2BBC62D8
gpg: Good signature from "Chris Yeo <yeochinyi@gmail.com>" [ultimate]
sed: 1: ":a;N;$!ba;s/\n/ n7dC1gz ...": unused label 'a;N;$!ba;s/\n/ n7dC1gzxa36v5vpfvhW7mgfcxxf7lDnm /g'
sed: 1: ":a;N;$!ba;s/\n/ n7dC1gz ...": unused label 'a;N;$!ba;s/\n/ n7dC1gzxa36v5vpfvhW7mgfcxxf7lDnm /g'
sed: 1: "/Users/yeochinyi/.zsh_h ...": unterminated transform source string

**Comment by wulfgarpro** [comment]
Can you please apply this, re-run and send me the output?

```
diff --git a/history-sync.plugin.zsh b/history-sync.plugin.zsh
index 7a1b03d..bc3bc54 100644
--- a/history-sync.plugin.zsh
+++ b/history-sync.plugin.zsh
@@ -12,6 +12,7 @@
 #   https://www.wulfgar.pro
 # ----------------------------------------------------------------
 #
+set -x
 autoload -U colors && colors

 alias zhpl=history_sync_pull
```

Also, can you please tell me the output from `sed --version`?

**Comment by yeochinyi** [comment]
I replace tr and sed with the gnu version from brew and it works. Thanks!

**Comment by wulfgarpro** [comment]
See #24.
