### ISSUE TITLE
Seeking clarification on `zhsync`

### ISSUE THREAD

**Issue by jarrodcolburn** [wulfgarpro/history-sync#21]
This looks absolutely amazing thanks so much. 
I'm doing a lot of work inside Containers where I'm constantly thinking "what was that command I ran in X environment?"
I just installed using `antidote`, setting up the  `repo` for my history and a `gpg` is my next step, but before I do...

A quick question though, and seeking clarification on the docs, specifically about the `zhsync` command as I couldn't tell in `README.md` or `zhsync --help`....

"Do I need to run `zhsync` as a cli command manually periodically? Or is it a background service/daemon that I start and stop? 

If the prior, any suggestions on me running it as a service? If I have to do it manually I will probably forget, or the container I want to sync will be stopped or deleted when I need to sync.

thanks again for all your 👍

**Comment by wulfgarpro** [comment]
> "Do I need to run zhsync as a cli command manually periodically? Or is it a background service/daemon that I start and stop?

It's just a shell wrapper so you'll have to use another mechanism to automate it like `cron`.
