### ISSUE TITLE
Error on pull

### ISSUE THREAD

**Issue by peterbladen** [wulfgarpro/history-sync#22]
When I do a zhpl I get the following -

gpg: encrypted with rsa4096 key, ID xxxx, created 2020-02-25
      "xxxx"
gpg: Signature made Thu 23 Mar 15:19:25 2023 GMT
gpg:                using RSA key xxxxx
gpg: Good signature from "xxxxx" [ultimate]
sed: 1: ":a;N;$!ba;s/\n/ pVeiz0P ...": unused label 'a;N;$!ba;s/\n/ pVeiz0PnBeyWcAN8UmndM4lv1ggDdWDb /g'
sed: 1: ":a;N;$!ba;s/\n/ pVeiz0P ...": unused label 'a;N;$!ba;s/\n/ pVeiz0PnBeyWcAN8UmndM4lv1ggDdWDb /g'
sed: RE error: illegal byte sequence
sed: 1: "/Users/xxx/.zsh_history": extra characters at the end of p command

**Comment by wulfgarpro** [comment]
You have an illegal byte sequence in your `.zsh_history`. This normally
means invalid UTF-8. The GNU version of `sed` doesn't error like this.

What version of `sed` are you using?

Can you try the following:

`LC_CTYPE=C zhpl`

**Comment by peterbladen** [comment]
I am using macOS Ventura and its sed version is 13.2.1 , I did look at my zsh_history I don't see any weird references

I tried the LC_CTYPE=C zhpl

slightly different error but same result

sed: 1: ":a;N;$!ba;s/\n/ WSv3ban ...": unused label 'a;N;$!ba;s/\n/ WSv3ban9mldLqK9ISxJZLieBB30rizUF /g'
