### ISSUE TITLE
Support for multiline commands, newline removed on sync

### ISSUE THREAD

**Issue by mullnerz** [wulfgarpro/history-sync#7]
Currently tool removes newline from multiline commands. 

Example:

Before zhsync:

```
: 1511025426:0; echo command1\
echo command2
```

After zhsync it will become:
```
: 1511025426:0; echo command1\echo command2
```

**Comment by wulfgarpro** [comment]
See change d543adc09d4ba2df5faecdd8d5cb7e2b4b6c9d1c.
